client/.eslintrc.js, client/tailwind.config.js
fontsize, textcolor, color를 config로 설정했습니다.
프로젝트에서 사용하는 값만을 정의했으므로 위의 3개 값은 config에 지정된 값만 사용해주세요~
추후 config가 추가 및 변경될 여지가 있어 이 브랜치는 클로즈 하지 않고 두겠습니다!
=> 💄 ui : tailwind config 설정

client/tailwind.config.js
tailwind config 와 daisy가 충돌, primary가 동작하지 않습니다. 이름을 main으로 변경했습니다.
=> 🩹chore : daisy와 충돌 수정

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePatchDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
=> ✨ Feat: 운동모집 글 PATCH API 구현

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePatchDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/mapper/ExerciseMapper.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
- 운동모집글의 상세 조회 GET API 구현 (member 부분 빠져있습니다.)
=> ✨ Feat: 운동모집 글 GET API (상세 조회)

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
- Exercise post/ patch/ delete api 에서 Member 와의 연관관계를 매핑하는 로직 구현
=> ♻️ Refactor: 운동모집 글과 회원 연관관계 매핑

client/tailwind.config.js
- drop shadow 추가
- white와 black 추가
- font size 추가
config extends 말고 theme에 넣으면 이 친구들만 쓸 수 있는 건지 몰랐네요 🥲
=> 💄ui : tailwind config 추가

server/src/main/java/com/ilchinjo/mainproject/domain/address/controller/AddressController.java, server/src/main/java/com/ilchinjo/mainproject/domain/address/dto/AddressResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/address/mapper/AddressMapper.java, server/src/main/java/com/ilchinjo/mainproject/domain/address/repository/AddressRepository.java, server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressService.java, server/src/main/java/com/ilchinjo/mainproject/domain/address/service/AddressServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/dto/MultiResponseDto.java
=> ✨ Feat: 주소 전체조회 API

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseService.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/dto/ProposalResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/mapper/ProposalMapper.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/repository/ProposalRepository.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalService.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
파트너가 정해지면 신청을 막을까 했지만, 또다시 당근마켓이 떠오르면서 굳이? 라는 생각이 들었습니다.
이부분은 논의가 필요해보이네요.
자기 자신을 신청할 수 없다는 내용도 요구사항 정의서에 없는데 논의가 필요해보입니다.
findVerified 메서드를 퍼블릭화 했습니다. 자세한 내용은 커밋메시지를 참고바랍니다.
=> ✨ Feat: 운친 함께하기 신청 POST API

client/src/components/UI/atoms/CommentBtn.js, client/src/components/UI/atoms/EditBtn.js, client/src/components/UI/atoms/ExerciseBtn.js, client/src/components/UI/atoms/LongBtn.js, client/src/components/UI/atoms/MiniBtn.js, client/src/components/UI/atoms/ShortBtn.js, client/src/components/UI/atoms/index.js
몇몇 컴포넌트에서 onClick이 빠져있어서 추가했습니다!
=> 🩹chore : onClick 이벤트 추가

client/src/assets/img/icons/downArrow.svg, client/src/components/UI/molecules/Dropdown.js, client/src/components/UI/molecules/MiniDropdown.js
작은 dropdown은 변경되는 스타일 값이 많아 새로 팠습니다~
=> ✨feat : dropdown 구현

client/src/components/UI/atoms/TextInput.js, client/src/components/UI/molecules/ArounderReview.js, client/src/components/UI/molecules/InputComments.js, client/src/components/UI/molecules/WriterDetail.js
=> ✨feat: Add Text MOLECULES

client/src/components/UI/atoms/CarouselBtn.js, client/src/components/UI/atoms/ExerciseBtn.js, client/src/components/UI/atoms/index.js, client/src/components/UI/molecules/Carousel.js, client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/UI/molecules/ExerciseCategory.js
구현 내용
- 글 상세 페이지 내의 이미지 캐러셀
- 홈 페이지 내의 운동 필터 캐러셀
- 글쓰기 페이지 내의 운동 카테고리 캐러셀
가로 스크롤 캐러셀이라 웹에서는 패드/매직마우스 등으로 당겨야 합니다...!
모바일 뷰에서는 터치 스크롤로 가능합니다.
=> ✨feat : 캐러셀 구현

client/src/components/UI/molecules/Applicant.js
=> ✨feat: Add molecules Aplicant

client/src/components/UI/atoms/ChooseBtn.js, client/src/components/UI/atoms/Datepicker.js, client/src/components/UI/atoms/index.js, client/src/components/UI/molecules/Dropdown.js, client/src/components/UI/molecules/GenderSelect.js, client/src/components/UI/molecules/TownSelect.js, client/src/components/UI/molecules/WriteDate.js, client/src/components/UI/molecules/WriteGenderSelect.js
=> ✨ Feat : 유저 선택요소 컴포넌트 구현

client/src/components/UI/atoms/MiniBtn.js, client/src/components/UI/molecules/ArounderReview.js, client/src/components/UI/molecules/ReviewMent.js, client/src/components/UI/molecules/index.js, client/src/components/UI/organisms/Modal.js, client/src/index.css
전달 내용
- 모달 오픈 페이지에서 모달 여닫는 함수, 리뷰점수 state props 전달 필요합니다.
- 임시로 Pretend 폰트를 전역 저장했습니다. 문제 있을 경우 이슈 올려주세요!
- molecule index를 생성했습니다.
수정 내용
- MiniBtn
- btn 클래스 삭제
- 데이지의 btn class 때문에 height가 적용되지 않는 오류가 있어서 삭제했습니다.
- ArounderReview
- Figma와 다른 마진값 수정
- 텍스트에 width제거
- text color 추가
- ReviewMent 
- color를 상위 컴포넌트에서 props로 내리도록 수정
=> ✨Feat : 리뷰 모달 구현

client/src/components/UI/atoms/CommentLayout.js, client/src/components/UI/atoms/ExerciseBtn.js, client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/atoms/WriterCommentLayout.js, client/src/components/UI/molecules/CommentViewer.js, client/src/components/UI/molecules/CommentViewer_X.js, client/src/components/UI/molecules/WriterCardLayouts.js, client/src/components/UI/molecules/WriterCardLayouts_X.js, client/src/components/UI/organisms/HomeContents.js, client/src/utils/getIcon.js
홈화면 카드 컴포넌트 구현했습니다.
기존 개발 내용에서 변경사항
- 운동 아이콘 랜더 함수 분리
- **답글 카드 atom 분리**
- **작성자 답글 카드 atom 분리**
=> ✨ Feat : 홈화면 카드 컴포넌트 구현

client/src/components/UI/organisms/MyInfo.js
=> ✨feat: mypage info 구현

client/src/assets/img/icons/recomment.svg, client/src/components/UI/atoms/CommentBtn.js, client/src/components/UI/atoms/TextInput.js, client/src/components/UI/atoms/WriterCommentLayout.js, client/src/components/UI/molecules/CommentViewer.js, client/src/components/UI/molecules/CommentViewer_X.js, client/src/components/UI/molecules/InputComments.js, client/src/components/UI/molecules/WriterCardLayouts.js, client/src/components/UI/molecules/WriterCardLayouts_X.js, client/src/components/UI/organisms/Comments.js
=> ✨feat: Add ORG Comments

client/src/components/UI/molecules/HistoryCards.js, client/src/components/UI/organisms/ArounderRecord.js, client/src/components/UI/organisms/Comments.js, client/src/components/UI/organisms/DetailContents.js
✨feat: Add ORG Arounder Record
=> ✨feat: Add ORG Arounder Record 

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/Proposal.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/entity/ProposalStatus.java
=> ✨ Feat: 신청 상태 추가

.gitignore, server/.gitignore, server/build.gradle, server/src/main/java/com/ilchinjo/mainproject/global/config/AppConfig.java, server/src/main/java/com/ilchinjo/mainproject/global/config/P6spySqlFormatConfiguration.java, server/src/main/resources/application.yml, server/src/main/resources/logback-spring.xml
=> ✨ Feat: logging 설정

client/src/components/UI/atoms/ImgAddBtn.js, client/src/components/UI/atoms/SignupImg.js, client/src/components/UI/atoms/index.js, client/src/components/UI/molecules/GenderSelect.js, client/src/components/UI/templates/RegisterTemplate.js, client/src/components/templates/RegisterTemplate.js
- SignUp의 아이콘 이미지 변경
- ImgAddBtn의 위치 수정
- GenderSelect 제목 수정
- 회원가입 페이지 템플릿 구현
=> ✨ Feat: 회원가입 페이지 템플릿 구현

client/src/components/UI/atoms/FileDeleteBtn.js, client/src/components/UI/atoms/LongBtn.js, client/src/components/UI/atoms/index.js, client/src/components/UI/molecules/AddFile.js, client/src/components/UI/molecules/index.js, client/src/components/UI/organisms/WriteContents.js, client/src/components/templates/WriteTemplate.js
- 파일 업로드 컴포넌트 구현
- x 버튼으로 삭제하는 로직 포함
- 글쓰기 페이지 템플릿 구현
리팩토링이 필수적일 것 같습니당
=> ✨feat: 글쓰기 템플릿 구현

client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/UI/organisms/HomeContents.js, client/src/components/templates/MainTemplate.js, client/tailwind.config.js
메인페이지 템플릿 구현했습니다~
ui부분 수정을 했는데 내일 바뀔지도 모르겠네요
카드 부분은 프롭스가 너무 많아서 데이터로 묶어보내고 이후에 구조분해할당하는 식으로 바꿨습니다~
=> ✨feat: 메인페이지 템플릿 구현

server/src/main/java/com/ilchinjo/mainproject/domain/comment/controller/CommentController.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/controller/MemberController.java, server/src/main/java/com/ilchinjo/mainproject/domain/proposal/controller/ProposalController.java, server/src/main/java/com/ilchinjo/mainproject/domain/review/controller/ReviewController.java
https://stackoverflow.com/questions/6845772/should-i-use-singular-or-plural-name-convention-for-rest-resources
=> :recycle: refactor: url 전부 복수형으로 통일

client/src/components/UI/molecules/HeaderLogo.js
=> ✨ feat: 툴팁 구현 및 프롭스 수정

client/src/components/UI/molecules/IdInput.js, client/src/components/UI/molecules/PasswordInput.js, client/src/components/templates/LoginTemplate.js
=> 🐛 Fix : 로그인 페이지 템플릿 수정

client/src/components/UI/atoms/MiniBtn.js, client/src/components/UI/molecules/ArounderReview.js, client/src/components/UI/molecules/HeaderLogo.js, client/src/components/UI/molecules/HistoryCards.js, client/src/components/UI/molecules/NicknameMypage.js, client/src/components/UI/organisms/ArounderRecord.js, client/src/components/UI/organisms/Drawer.js, client/src/components/UI/organisms/Modal.js, client/src/components/UI/organisms/MyInfo.js, client/src/components/templates/MypageTemplate.js, client/src/index.css
- 어플리케이션 전체적으로 삽입 되어야 하는 스타일 설정
- Mypage 템플릿 구현
- 관련 컴포넌트 props로 내리도록 수정
=> ✨Feat: Mypage 템플릿 구현

server/.gitignore, server/build.gradle, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePostDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/config/AwsS3Config.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/controller/ImageController.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/dto/ImageResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/mapper/ImageMapper.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/repository/ImageRepository.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/service/ImageService.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/service/ImageServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPostDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberResponseDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java, server/src/main/resources/application-server.yml, server/src/main/resources/application.yml
=> ✨ Feat: 이미지 처리 로직 구현

server/src/main/java/com/ilchinjo/mainproject/domain/member/dto/MemberPatchDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/entity/Member.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacelong/NotSpaceLong.java, server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacelong/NotSpaceLongValidator.java, server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacestring/NotSpaceString.java, server/src/main/java/com/ilchinjo/mainproject/global/validator/notspacestring/NotSpaceStringValidator.java
- 주소 수정 : optional로 변경
- 닉네임 수정 : optional로 변경
- 커스텀 어노테이션 적용
=> 🐛 Bug: 회원 정보 수정 로직 변경

server/src/main/resources/application-common.yml, server/src/main/resources/application-local.yml, server/src/main/resources/application-server.yml
- common yml 파일 생성
- profile : local/ server 분리
=> 🩹 Chore: yml profile 설정

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java
운동모집 상세 조회 응답에 host/ proposals 정보 포함시켰습니다!
=> ♻️ Refactor: 운동모집 상세 조회에 host/proposal 정보 포함

client/src/components/UI/molecules/DropdownCity.js, client/src/components/pages/Register.js
=> ✨ Feat : 회원가입 페이지 추가 구현

client/src/App.js, client/src/components/pages/Main.js
=> ✨ Feat : 메인 페이지 추가 구현

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
- 운동모집글 delete 핸들러 메서드의 파라미터를 Long -> String 으로 변경
=> :adhesive_bandage: Chore: 운동모집글 삭제 핸들러메서드 파라미터 변경

server/src/main/java/com/ilchinjo/mainproject/domain/address/entity/Address.java, server/src/main/resources/data.sql
변경된 쿼리문은 제약조건 오류가 나면 프로그램 실행이 안돼서 넣었습니다.
insert ignore into ~~ 도 가능합니다.
=> 🐛 Bug: 실행시마다 주소가 중복되어 저장되는 문제 수정

server/src/main/java/com/ilchinjo/mainproject/domain/comment/service/CommentServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
hasnext 버그를 수정함과 동시에 성능도 개선했습니다.
한개 더 쿼리해서 있는지 없는지 파악하는 형식 입니다.
=> 🐛 Bug: hasNext 버그 수정 및 성능 개선

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/controller/ExerciseController.java
- 운동모집 전체조회에도 Long memberId 로 받고 있던 것을 String token 으로 변경하였습니다!
=> 🐛 Bug: 운동모집글 전체조회 핸들러메서드 파라미터 변경

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
- 운동시작 시간이 종료 시간보다 늦을 경우 예외를 발생시키는 로직을 추가하였습니다.
=> :bug: Bug: 운동시작 시간이 종료시간보다 늦을 경우의 예외처리 로직 생성

server/src/main/java/com/ilchinjo/mainproject/domain/proposal/mapper/ProposalMapper.java
https://www.baeldung.com/mapstruct#2-the-mapper-interface-1 이곳을 참조하였습니다. https://stackoverflow.com/questions/48521903/map-custom-method-mapper-to-mapstruct 여기에 소개된 방법으로 메핑할 메서드를 설정할 수도 있습니다.
=> 🐛  Fix: proposalStatus가 null로 나오던 문제 수정

client/src/components/UI/atoms/LongBtn.js, client/src/components/UI/atoms/Toggle.js, client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/pages/Login.js, client/src/components/pages/Main.js, client/src/components/pages/Register.js, client/src/utils/getIcon.js
로그인 페이지 완료
회원가입 주소 제외 완료
메인 주소 및 추가 API 대기중
=> ✨ Feat: 데이터 패칭 

client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/molecules/DropdownCity.js, client/src/components/UI/molecules/MiniDropdown.js, client/src/components/UI/molecules/TownSelect.js, client/src/components/UI/organisms/HomeContents.js, client/src/components/pages/Login.js, client/src/components/pages/Main.js, client/src/components/pages/Register.js
주소 관련해서 일단 연결해놨습니다.
메인 카드 컴포넌트또한 이미지 관련 제외하고는 확인 완료했습니다!
=> ✨ feat: 데이터 추가 연결

client/src/components/UI/organisms/index.js
🩹chore: code del comments by index.js
=> 🩹chore: code del comments by index.js

client/src/components/UI/atoms/EditBtn.js, client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/molecules/DropdownCity.js, client/src/components/UI/molecules/MiniDropdown.js, client/src/components/UI/organisms/HomeContents.js, client/src/components/pages/Main.js, client/src/components/pages/Register.js
메인페이지 추가 구현입니다~ 주소부분 맞춰 조정해놓고 임시로 짜놨습니다!
=> ✨Feat: 메인페이지 추가 구현

client/src/components/UI/molecules/HeaderLogo.js, client/src/components/UI/organisms/HomeContents.js, client/src/components/pages/Main.js, client/src/components/pages/MypageTemplate.js
=> ✨ feat: 메인페이지 추가 구현

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExerciseDetailResponseDto.java
- ExerciseDetailsResponseDto에 images 필드 추가했습니다.
=> :adhesive_bandage: Chore: ExerciseDetailResponseDto에 images 추가

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/atoms/Toggle.js, client/src/components/UI/organisms/HomeContents.js, client/src/components/pages/Main.js, client/src/recoil/atoms.js
=> #174 ✨메인페이지 추가 구현

client/src/components/UI/molecules/DropdownCity.js, client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/UI/molecules/HeaderLogo.js, client/src/components/pages/Login.js
=> ✨ feat: 메인페이지 추가수정

client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/molecules/DropdownCity.js, client/src/components/pages/Main.js
수정완료했습니다~ 로직 그냥 바꿨어요! 좀 더 개선이 됐습니다 핫핫
=> 🐛 fix: 분기 로직 변경 및 개선 완료

client/package-lock.json, client/src/components/UI/atoms/CommentDeleteBtn.js, client/src/components/UI/atoms/TextInput.js, client/src/components/UI/molecules/Applicant.js, client/src/components/UI/molecules/Carousel.js, client/src/components/UI/molecules/InputComments.js, client/src/components/UI/organisms/DetailContents.js, client/src/components/UI/organisms/DetailContentsWriter.js, client/src/components/UI/organisms/ViewerComments.js, client/src/components/UI/organisms/WriterComments.js, client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js, client/src/components/pages/Landing.js, client/src/components/pages/Main.js
=> ✨feat: 상세페이지 70% 정도 구현 

client/src/client/client.js, client/src/components/UI/atoms/HomeCardImg.js
=> ✨feat: 클라이언트 디폴트 및 인터셉터 진행중

client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js
🩹chore: ArounderViewer props 정정
=> 🩹chore: ArounderViewer props 정정

client/src/components/pages/Mypage.js
또 빼먹었어요 이슈넘버링....
마이페이지에서 이미지 랜더 안되는거 체이닝으로 해결했습니다
=> 🚑Hotfix: 마이페이지 랜딩 오류 해결

client/package-lock.json, client/package.json, client/src/components/pages/Main.js, client/src/index.css, client/tailwind.config.js
=> ✨feat: 드로워 추가

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/dto/ExercisePatchDto.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/entity/Exercise.java, server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/image/entity/Image.java
운동모집 글을 수정할 때 이미지 또한 수정가능하도록 변경하였습니다.
=> 🐛 Bug: 운동모집글 수정에 누락됐던 이미지 수정 로직 추가

server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
한 사람이 동일한 운동모집글에 중복 신청을 할 수 없는 로직을 추가하였습니다.
=> 🐛 Bug: 동일한 사람이 여러번 신청할 수 없는 로직 추가

client/src/components/UI/atoms/ShortBtn.js, client/src/components/UI/molecules/ArounderReview.js, client/src/components/UI/molecules/HistoryCards.js, client/src/components/UI/molecules/NicknameMypage.js, client/src/components/UI/organisms/Modal.js, client/src/components/UI/organisms/MyInfo.js, client/src/components/pages/Mypage.js
마이페이지의 랜더링 오류 원인을 찾아 해결했습니다.
원인: 이미지가 없는 유저인 경우 image.remotePath가 존재하지 않아서 에러
if 분기처리로 해결했습니다~!
=> 🚑hotfix: 마이페이지 이미지 렌더 오류 수정

server/src/main/java/com/ilchinjo/mainproject/domain/auth/controller/AuthController.java, server/src/main/java/com/ilchinjo/mainproject/domain/auth/repository/RefreshTokenRepository.java, server/src/main/java/com/ilchinjo/mainproject/domain/auth/service/AuthService.java, server/src/main/java/com/ilchinjo/mainproject/domain/auth/service/AuthServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberService.java, server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/advice/GlobalExceptionAdvice.java, server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java, server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtAuthenticationFilter.java, server/src/main/java/com/ilchinjo/mainproject/global/security/filter/JwtVerificationFilter.java, server/src/main/java/com/ilchinjo/mainproject/global/security/handler/MemberAuthenticationEntryPoint.java, server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtStatus.java, server/src/main/java/com/ilchinjo/mainproject/global/security/jwt/JwtTokenizer.java, server/src/main/java/com/ilchinjo/mainproject/global/security/utils/ErrorResponder.java
- Refresh 요청으로 재발급된 Access Token이 이후 검증에서 유효한지 확인했습니다.
- Access Token 및 Refresh Token이 만료된 경우와 Refresh Token이 데이터베이스에 저장된 토큰과 일치하지 않을 경우 응답 메시지 "Jwt token has expired"을 전달합니다.
- 요청 시 쿠키에 Refresh Token이 담겨 있지 않은 경우 응답 메시지 "Required request cookie is missing"을 전달합니다.
=> ✨ Feat: Refresh POST API 생성

client/src/components/UI/atoms/TextInput.js, client/src/components/UI/molecules/CommentViewer_X.js, client/src/components/UI/molecules/InputComments.js, client/src/components/UI/molecules/WriterCardLayouts_X.js, client/src/components/UI/organisms/ViewerComments.js, client/src/components/UI/organisms/WriterComments.js, client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js
✨feat: (대)댓글 작성/삭제 구현 && 게시물 수정/삭제 구현
=> ✨feat: (대)댓글 작성/삭제 구현 && 게시물 수정/삭제 구현 

client/src/components/pages/Login.js, client/src/components/pages/Main.js
=> #218 🩹chore: 무한스크롤 사이즈 조절 및 로그인 이슈

server/src/main/java/com/ilchinjo/mainproject/domain/member/service/MemberServiceImpl.java, server/src/main/java/com/ilchinjo/mainproject/global/exception/ExceptionCode.java
- 닉네임 중복일 때 새로운 에러코드를 생성하여 적용시켰습니다.
=> ✨ Feat: 닉네임 중복일 때 에러코드 생성

client/src/components/pages/Login.js, client/src/components/pages/Main.js, client/src/components/pages/Register.js
=> ✨feat: 이메일,닉네임 중복 알림 처리

client/src/components/UI/molecules/Applicant.js, client/src/components/UI/organisms/ViewerComments.js, client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js
=> #235 ✨feat: 뷰어 기준 함께하기 신청 가능

client/src/components/UI/atoms/Datepicker.js, client/src/components/UI/atoms/LongBtn.js, client/src/components/UI/atoms/WriteContentsInput.js, client/src/components/UI/atoms/WriteTitleInput.js, client/src/components/UI/molecules/AddFile.js, client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/UI/molecules/ExerciseCategory.js, client/src/components/UI/molecules/WriteDate.js, client/src/components/UI/molecules/WriteGenderSelect.js, client/src/components/UI/molecules/WriteHNC.js, client/src/components/UI/organisms/WriteContents.js, client/src/components/pages/ArounderWriter.js, client/src/components/pages/Write.js
- 이미지 없을 때도 글 쓰기 가능
- 카테고리 캐러셀에서 ALL 제거
- 게시글 수정 로직 구현
- 이미지 수정 추가
- 날짜 버그 수정
=> 🐛Bug: 글쓰기 페이지 버그 수정

client/src/components/UI/atoms/CommentLayout.js, client/src/components/UI/atoms/WriterCommentLayout.js, client/src/components/UI/molecules/Applicant.js
🩹chore : 무한 리렌더링 방지 및 댓글 창 높이 제한 해제
=> 🩹chore : 무한 리렌더링 방지 및 댓글 창 높이 제한 해제

client/src/components/UI/molecules/HeaderLogo.js, client/src/components/UI/organisms/Drawer.js, client/src/components/pages/Main.js, client/src/components/pages/Register.js
회원가입 버튼 css
헤더 수정, 햄버거 커서 포인터 추가
이미지 경로 수정
로그아웃 엑세스 토큰 삭제
=>  #211 ✨feat: 드로워 추가 기능 구현

client/src/components/UI/atoms/CarouselBtn.js, client/src/components/UI/molecules/Applicant.js, client/src/components/UI/molecules/Carousel.js, client/src/components/UI/organisms/WriterComments.js, client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js
=> ✨feat: 어라운더 신청하기/확정하기 구현

client/src/client/client.js, client/src/components/pages/Login.js, client/src/components/pages/Main.js
drawer, client, login 부분 수정합니다.
=> 🩹 chore: drawer 및 client 수정

client/src/components/pages/Login.js
=> #211 🩹chore: 메인 게시글 첫 랜딩 401 에러 수정완료

client/src/components/UI/molecules/NicknameMypage.js, client/src/components/UI/organisms/MyInfo.js, client/src/components/pages/Main.js, client/src/components/pages/Mypage.js
이미지 렌더 지연 문제 해결
로컬스토리지에  memeberId추가
@seunghw 
Main.js에서 setUserId가 삭제되어있던데 안 쓰는 건가용?
pull당겨왔더니 해당 부분 conflict나서 물어봅니당
=> 🐛bug: 마이페이지 렌더 지연 문제 해결

client/src/client/client.js, client/src/components/UI/molecules/Applicant.js, client/src/components/UI/molecules/HeaderLogo.js, client/src/components/UI/organisms/Drawer.js, client/src/components/pages/Login.js, client/src/components/pages/Main.js, client/src/components/pages/Mypage.js, client/src/components/pages/Register.js
=> 🩹chore: Applicant 수정

client/src/components/pages/Main.js
=> ✅ test: 쿠키 테스트

client/src/client/client.js
=> ✅ test: client 수정

client/src/components/UI/molecules/ExerciseCarousel.js, client/src/components/UI/molecules/HeaderLogo.js
헤더를 모바일처럼 보일 수 있게 fixed로 변경했습니다.
=> ✨ feat: 헤더 ui 추가

client/src/components/UI/atoms/HomeCardLayouts.js, client/src/components/UI/molecules/Applicant.js, client/src/components/UI/organisms/DetailContents.js, client/src/components/UI/organisms/DetailContentsWriter.js, client/src/components/pages/ArounderViewer.js, client/src/components/pages/ArounderWriter.js
=> ✨feat: 어플리컨트 해결 및 버그 픽스 등

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/repository/ExerciseRepositoryImpl.java
GenderType Querydsl 부분을 수정하였습니다.
=> :recycle: Refactor: GenderType Qureydsl 수정

client/src/components/UI/molecules/Carousel.js
=> 🩹chore : 캐러셀 수정

client/src/client/client.js, client/src/components/UI/molecules/HeaderLogo.js, client/src/components/UI/organisms/Drawer.js, client/src/components/UI/organisms/MyInfo.js, client/src/components/pages/Main.js, client/src/components/pages/Mypage.js
=> ✨ feat: refresh 토큰 추가 설정

server/src/main/java/com/ilchinjo/mainproject/domain/proposal/service/ProposalServiceImpl.java
운동 신청의 수락 로직에 시간 제약 조건을 추가하였습니다.
=> :bug: Bug: 수락 로직에 시간 제약 조건 설정

server/src/main/java/com/ilchinjo/mainproject/global/controller/HealthCheckController.java, server/src/main/java/com/ilchinjo/mainproject/global/security/config/SecurityConfiguration.java
=> ✨ Feat: healthcheck api 생성

client/src/components/UI/molecules/CommentViewer_X.js, client/src/components/UI/molecules/HistoryCards.js, client/src/components/UI/organisms/Modal.js, client/src/components/pages/Mypage.js, client/src/components/pages/Write.js, client/src/index.css
=> 🐛Fix: 마이페이지 버그 수정

Readme.md
=> 🩹chore: 리드미 수정

server/src/main/java/com/ilchinjo/mainproject/domain/exercise/service/ExerciseServiceImpl.java
운동모집글 수정시에도 시간 제약 조건을 추가하였습니다.
=> :bug: Bug: 운동모집글 수정시에도 시간제약 조건 추가

server/src/main/java/com/ilchinjo/mainproject/domain/review/dto/ReviewPostDto.java
원시타입의 경우 @ NotNull을 무시하고 기본값으로 들어가는 문제 해결
=> 🐛 Bug: 모든 post patch dto에서 원시타입 제거

client/src/components/UI/organisms/ViewerComments.js, client/src/components/UI/organisms/WriterComments.js, client/src/components/pages/ArounderWriter.js
=> 🐛bug: QA 버그 수정 완료

client/src/components/UI/organisms/HomeContents.js
=> #298 🐛 Bug : 메인페이지 카드 수정

client/src/components/UI/molecules/Applicant.js
=> 🐛bug: 어라운더 확정 하기 전에 알림 창 추가

client/src/components/UI/molecules/Applicant.js, client/src/components/UI/organisms/ViewerComments.js
=> #302 🐛 Bug : key 에러 수정

client/src/components/pages/Main.js
=> #298 🐛 Fix : cursorId 수정

client/src/components/pages/ArounderWriter.js
=> 🐛bug: 대댓글 밸류값 수정

client/src/components/pages/Main.js
=> 🐛 Fix : 무한스크롤 수정
